### ISSUE TITLE
Cannot create property '__metadata' on number '5' ( intermittent ) 

### ISSUE THREAD

**Issue by sreehari-pillai-atom** [cap-js-community/odata-v2-adapter#108]
I have an association from /Materials(key)?$expand=ItsMaterialType/ItsText , where ItsMaterialType ( corresponding entity ) has a LargeString in its property. This call gives 500 , intermittent , the below stack trace. Running the same URL again works perfectly. Something to do with cache ? 

```
{
"stacktrace": [
      "TypeError: Cannot create property '__metadata' on number '5'",
      "at addMetadata (/home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3650:21)",
      "at /home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3561:7",
      "at Array.forEach (<anonymous>)",
      "at convertResponseData (/home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3560:10)",
      "at /home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3539:13",
      "at Array.forEach (<anonymous>)",
      "at /home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3530:25",
      "at Array.forEach (<anonymous>)",
      "at convertResponseData (/home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3529:10)",
      "at convertResponseBody (/home/vcap/app/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3388:11)"
    ]
}
```

**Comment by oklemenz2** [comment]
I will check

**Comment by oklemenz2** [comment]
BTW. Which version of `@cap-js-community/odata-v2-adapter` do you use? Line `3650` does not match `addMetadata` function.

Can you try latest version: `1.13.8`

**Comment by sreehari-pillai-atom** [comment]
this is the abstract - meanwhile let be change to 1.13.8 and give it a try. My primary observation is, I had a GET call to another API , with in which I am updating a table. The immediate GET call to an unrelated entity was throwing 404 / 500 randomly  - I suspect some sort of a db lock or so for the 404. 500 is due the the metadata caching ? 

I commented the DB update and its smooth for now. Somewhere its inconsistent 


`entity Materials 
{
key ID : Integer; 
      MATERIAL_TYPE_ID : Integer ; 
      ItsMaterialType : Association to one MaterialType on ItsMaterialType.ID = $self.MATERIAL_TYPE_ID; 
}
entity MaterialType 
{
    key ID : Integer ; 
    DESCRIPTION : LargeString;
    TEXT_ID : Integer; 
     ItsText : Association to one MaterialTypeText on ItsText.ID = $self.TEXT_ID ; 
}

entity MaterialTypeText 
{
key ID : Integer ; 
TEXT : LargeText ; 
}
`

**Comment by oklemenz2** [comment]
Thanks for the model. I looks very common, but I will check.

You can explain where the `5` is coming from in `Cannot create property '__metadata' on number '5'"`?
Do you have the payload of that response, that is coming to the OData V2 adapter?

Do you have a new callstack trace when the exception happens, so that I at least can match the line, where the error occurs?

I don't think it's related to any caches, but it seems to be a race condition... Are use missing an `await` somewhere in your handlers GET api call? That could explain this behavior?...

**Comment by oklemenz2** [comment]
I provided a fix, that prevents the crashing of response conversion: https://github.com/cap-js-community/odata-v2-adapter/commit/890b8badc3a5e196c64dae1138f3dc871ac4c686

Will be part of next release, beginning of next year.

Still I guess the OData V4 response is malformed in some cases, so you should check, why you have a number `5` in our response payload for and expand element, which normally should be an object or array of objects...

**Comment by sreehari-pillai-atom** [comment]
Awesome. Let me test this commit

**Comment by Caisi** [comment]
Hello, any update on this issue? I have a similar problem. When I tested fix you provided locally it helped. 
When could we expect new patch version release? Thanks.

**Comment by oklemenz2** [comment]
I will release on Tuesday morning.

**Comment by oklemenz2** [comment]
1.14.0 is released: https://github.com/cap-js-community/odata-v2-adapter/releases/tag/v1.14.0
Please check.

**Comment by Caisi** [comment]
The issue is gone. Thanks a lot @oklemenz2.

**Comment by sreehari-pillai-atom** [comment]
Its gone. Awesome !
