### ISSUE TITLE
Error to display tree structure for cds 8.1.1

### ISSUE THREAD

**Issue by FedorSh-illumiti** [cap-js-community/odata-v2-adapter#59]
Hi. I am using this library to display a tree hierarchy for SAP CAP application. Everything is working fine with the 7.9.3 but with the latest version of cds I am getting the error TypeError: Cannot create property '__metadata' on string '0'. 
Request: 
ChangeOrders?$filter=level%20eq%200%20and%20(projectStatus_code%20eq%20%27AllProjects%27)&$select=projectElement%2cprojectDescription%2crespPerson%2fPersonFullName%2cattachment%2cstatus%2fdescr%2ctotal%2ctotalCurrency%2cchangedOn%2cprojectElementUUID%2cproject%2fProjectUUID%2clevel%2cparent_node%2chierarchyNode%2cdrilldownState&$expand=respPerson%2cstatus&$skip=0&$top=138&$inlinecount=allpages
Error and stack:
Batch: TypeError: Cannot create property '__metadata' on string '0'
    at addMetadata (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3630:21)
    at /Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3553:7
    at Array.forEach (<anonymous>)
    at convertResponseData (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3552:10)
    at convertResponseData (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3513:14)
    at /Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3539:11
    at Array.forEach (<anonymous>)
    at /Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3522:25
    at Array.forEach (<anonymous>)
    at convertResponseData (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3521:10)
    at convertResponseBody (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:3380:11)
    at /Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:2856:28
    at /Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:4770:30
    at Array.forEach (<anonymous>)
    at processMultipartMixed (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:4756:11)
    at ProxyServer.convertProxyResponse (/Users/fedorshestov/Documents/Projects/Production/sbi-sap.pcom-cap/node_modules/@cap-js-community/odata-v2-adapter/src/index.js:2843:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

UI - smart component SmartTable with type tableType="TreeTable"
Annotations:
      @sap.hierarchy.node.for
      hierarchyNode        : String(30);

      @sap.hierarchy.level.for
      level                : Integer;

      @sap.hierarchy.parent.node.for
      parent_node          : String(30);

      @sap.hierarchy.drill.state.for
      drilldownState       : String(30) enum {
        expanded;
        collapsed;
        leaf
      };

**Comment by oklemenz2** [comment]
Thanks for reporting this issue. We will have a look, and provide a solution asap.

**Comment by oklemenz2** [comment]
I tried to reproduce the issue, but for me the hierarchy queries work. So something is different in your model.

Would it be possible to share a minimal example, that makes it easy to reproduce the issue.
That would help a lot.

**Comment by oklemenz2** [comment]
I would recommend to open an issue to the SAP Cloud Application Programming Model via support channels:
https://cap.cloud.sap/docs/resources/#support-channels

It looks to me, that the data responded for your OData V4 request is wrong (Array of `0`).

Can you activate payload logging via env `CDS_LOG_LEVELS_COV2AP=debug`

Can you post here the OData V4 response body of the failing OData request once with CDS 7.9 and once with CDS 8.1?

**Comment by oklemenz2** [comment]
No activity since two weeks, therefore I close this issue. Feel free to reopen, with additional information, or use for CAP support channels...
